x=int(input('enter first number '))
y=int(input('enter the second number '))
print("the addition of two numbers are",x+y)
print("the subtraction of two numbers are",x-y)
print("the multiplication of two numbers are",x*y)
print("the division of two numbers are",x/y)
print("the modulus of two numbers are",x%y);print("the flooring division of two numbers are",x//y)
print('is',x, '=' ,y,'?',x==y)
print('is',x, '<=' ,y,'?',x<=y)
print('is',x, '>=' ,y,'?',x>=y)
print('is',x, '!=' ,y,'?',x!=y)
print('is',x, '<' ,y,'?',x<y)
print('is',x, '>' ,y,'?',x>y)
