
import com.sun.xml.internal.ws.wsdl.parser.InaccessibleWSDLException;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javafx.beans.property.DoubleProperty;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cs_loneranger_
 */
public class add_sells extends javax.swing.JFrame {
    Connection connect;
Statement stmt;
ResultSet rs,rs2,rs3;
String a=null;
String b=null;
String check_in=null;
String check_in1=null;
String nam=null,num=null;
String order=null,delpro=null;
 String store_id=null,GST=null;
int point=0,total=0;float quan=0;
float ttl=0;
float mrp=0,pnt=0;
 String p = null;
public void empis(String id,String bill_no,String in,String in1,String name){
    a=id;
    b=bill_no;
    check_in=in;
    check_in1=in1;
    nam=name;
}

    /**
     * Creates new form add_sells
     */
    public add_sells() {
        initComponents();
        Connectivity();
      jPanel2.setBackground(new Color(0,0,0,50));
        AutoCompleteDecorator.decorate(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Connectivity()
    {
        try{
       connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/provisionstore","root","tiger");
       stmt=connect.createStatement();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        try{
            String sql1="select * from productmanagement";
           jPanel2.setVisible(false);
           jPanel4.setVisible(false);
           jPanel5.setVisible(false);
           jLabel12.setVisible(false);
           jLabel14.setVisible(false);
           jLabel15.setVisible(false);
            rs=stmt.executeQuery(sql1);
            //DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
            //model.setRowCount(0);
            while (rs.next()) {
              jComboBox1.addItem(rs.getString("product_name"));
                
            }
            
            
            //rs.getString("emp_ID")
           
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, "empty relation");
            
        }
    }
           
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BILLING SITE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Customer Name");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(28, 70, 143, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(190, 60, 266, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Phone Number");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 120, 121, 17);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(190, 112, 270, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("NET BANKING");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(350, 250, 135, 25);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("CARD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(190, 250, 73, 25);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(700, 90, 116, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CASH");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(610, 90, 40, 17);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("POINTS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(620, 250, 89, 25);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Enter the phone number");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(220, 160, 215, 17);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 1000, 530));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sales Dashboard");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 168, 31));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 79, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Sales Product");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 159, 139, 27));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ITEMS", "---------------------------------------------------------------------------------------------" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 153, 266, 37));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(102, 102, 102)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Type", "Cost Per Unit", "Quantity", "Discount", "Title 6"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 197, 1228, 132));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 164, 101, -1));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jSpinner1.setRequestFocusEnabled(false);
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 153, 196, 37));
        jSpinner1.getAccessibleContext().setAccessibleName("");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add to cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1196, 160, 120, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel1.setText("Sales Dashboard");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("CUSTOMERS POINTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("ITEM DETAILS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(568, 568, 568)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton8))
                    .addComponent(jButton4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1969, 57));

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total Cost:");

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Save Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store_images/cart.jpg"))); // NOI18N
        jLabel6.setText("CART");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("NO OF ITEMS:");

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("POINTS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton9))
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1504, 126, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Empty cart not allowed");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 165, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 255, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("MOBILE NUMBER");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1504, 517, 370, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store_images/bill.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 102));
        jLabel14.setText("Enter The Correct Amount");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 960, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(jComboBox1.getSelectedIndex()==0||jSpinner1.getValue().equals("0.00")){
           jLabel12.setVisible(true);
       }
       else{
       try{
          jLabel12.setVisible(false);
           String sql7="select store_id,GST from store";
        rs=stmt.executeQuery(sql7);
        if(rs.next()){
            store_id=rs.getString("store_id");
            GST=rs.getString("GST");
        }
       }
       catch(SQLException s){
           
       }
       try{
        String discount=null;
        String lic_no=null;
        String cost=null;
        String typ=null;
        float disc_mrp=0;
        int sl=0;
        String sql1="select * from productmanagement where product_name='"+jComboBox1.getSelectedItem()+"'";
       
         
        
         rs=stmt.executeQuery(sql1);
        
           while(rs.next()){
               p=rs.getString("product_name");
               cost=rs.getString("cost");
               typ=rs.getString("type");
               lic_no=rs.getString("lic_no");
               discount=rs.getString("discount");
               disc_mrp=rs.getFloat("disc_mrp");
           }
           float q=(float)jSpinner1.getValue();
          System.out.println(q);
           DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
           DateTimeFormatter dtf2=DateTimeFormatter.ofPattern("yyyy-MM-dd");

           DateTimeFormatter dtf1=DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
           LocalDateTime now=LocalDateTime.now();
        String sql4="select count(*) from addsells where order_no='"+b+"'";
        rs=stmt.executeQuery(sql4);
        
        if(rs.next()){
            sl=rs.getInt("count(*)");
            sl++;
        }
        mrp=Float.parseFloat(cost)*q;
        ttl=(Float.parseFloat(cost)*q)-((Float.parseFloat(cost))*q*(Float.parseFloat(discount))/100);
           String sql2="insert into addsells values("+sl+",'"+p+"','"+typ+"',"+q+",'"+cost+"',"+disc_mrp+","+mrp+","+ttl+",'"+b+"','"+a+"','"+GST+"','"+store_id+"','"+check_in+"')";
           
         int n= stmt.executeUpdate(sql2);//executeUpdate saves the data into the table 
            if(n==1){
                JOptionPane.showMessageDialog(this, n + " records saved successfully");
                 jPanel4.setVisible(true);
           }
            
        
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);//jTextField5.getText()+"\n already exist");
        } 
        try{
            //String item=(String)jComboBox1.getSelectedItem();
            String sql1="select * from addsells where order_no='"+b+"'";
            rs=stmt.executeQuery(sql1);
            
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("product_name"),rs.getString("type"),rs.getString("mrp_cost"),rs.getString("quantity"),rs.getString("disc_mrp"),rs.getString("disc_total")});
                quan=rs.getFloat("quantity");
            }
            
            String sql5="select sum(disc_total),max(sl_no) from addsells where order_no='"+b+"'";
            rs=stmt.executeQuery(sql5);
            while(rs.next()){
                jLabel8.setText("Total Cost:"+rs.getString("sum(disc_total)"));jLabel11.setText("No of Items: "+rs.getString("max(sl_no)"));
                 point=rs.getInt("sum(disc_total)");
            }
            try{
                String sql="update productmanagement set total_item=total_item-"+quan+" where product_name='"+p+"'";
                stmt.executeUpdate(sql);
            }
            catch(SQLException s){
                
            }
           
            
           
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
            
        }}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        DateTimeFormatter dtf1=DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
           LocalDateTime now=LocalDateTime.now();
        try{
            jPanel5.setVisible(false);
           order="pic"+dtf1.format(now);
             jPanel2.setVisible(true);
             if(point>=10000 || point==0){
                 jLabel15.setVisible(true);
             }
             else{
                 jLabel15.setVisible(false);
             }
             String sql="update addsells set order_no='"+order+"' where order_no='"+b+"'";
             int n=stmt.executeUpdate(sql);
             
        }
       catch(SQLException e){
           
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
        try{
        int row=jTable1.getSelectedRow();
        
        if(row>=0){
            int sel=JOptionPane.showConfirmDialog(this,"do you want to delete?","",JOptionPane.YES_NO_OPTION);
            if(sel==0){
           
                 try{
                    String sql1="select product_name,sl_no,quantity from addsells where product_name='"+model.getValueAt(row, 0).toString()+"' and order_no='"+b+"'";
                     rs=stmt.executeQuery(sql1);
                     while(rs.next()){
                         p=rs.getString("sl_no");
                         quan=rs.getFloat("quantity");
                         delpro=rs.getString("product_name");
                     }
            String sql="delete from addsells where sl_no='"+p+"' and order_no='"+b+"'";
            int n= stmt.executeUpdate(sql);//executeUpdate saves the data into the table 
            String sql2="update productmanagement set total_item=total_item+"+quan+" where product_name='"+delpro+"'";
                stmt.executeUpdate(sql2);
            if(n==1){
                JOptionPane.showMessageDialog(this, n + " record deleted successfully");
               
                model.removeRow(jTable1.getSelectedRow());
                  String sql5="select sum(disc_total),max(sl_no) from addsells where order_no='"+b+"'";
            rs=stmt.executeQuery(sql5);
            while(rs.next()){
                 jLabel8.setText("Total Cost:"+rs.getString("sum(disc_total)"));jLabel11.setText("No of Items: "+rs.getString("max(sl_no)"));
                point=rs.getInt("sum(disc_total)");
            }
               
                }
            else{
                JOptionPane.showMessageDialog(this, "lic ID:\n not found");
            }
        }
        catch(SQLException s){
            JOptionPane.showConfirmDialog(this,"lic ID:\n not found");
        } 
       
            }
        }
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
      
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
            LocalDateTime now=LocalDateTime.now();
             String bill_no=null;
              try{
           String sql1="select count(distinct(order_no)) from addsells where dte='"+check_in+"' and employee_id='"+a+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               String sql2="insert into emp_work values('"+a+"','"+nam+"','"+check_in1+"','"+dtf.format(now)+"','"+check_in+"',"+rs.getString("count(distinct(order_no))")+")";
               stmt.executeUpdate(sql2);
               LOGIN_PAGE lp=new LOGIN_PAGE();
               lp.setVisible(true);
               dispose();
           }
       }
       catch(SQLException s){
           
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
      
            try{
           String sql1="select phone_no,points from customer where phone_no='"+jTextField2.getText()+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               if(point>=10000){
               String sql2="update customer set points="+(Float.parseFloat(rs.getString("points"))+point/100)+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");
           }
               else{
                     String sql2="update customer set points="+(Float.parseFloat(rs.getString("points")))+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");
               }
           }
           else{
                if(point>=10000){
            String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"',"+point/100+",'"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
             receipt rpt=new receipt();
                   }
            else{
                String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','0.00','"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
                   }
           }
       }
       catch(SQLException e){
           
       }
       
         try{
               String amt=jTextField3.getText();
        double pay=Double.parseDouble(amt)-point;
        if(pay>=0){
            jLabel14.setVisible(false);
             String sq="select cust_id from customer where phone_no='"+jTextField2.getText()+"'";
             rs=stmt.executeQuery(sq);
             if(rs.next()){
          
           String sql1="insert into payment values('CASH',"+point+","+amt+","+pay+",'"+rs.getString("cust_id")+"','"+order+"')";
           int n=stmt.executeUpdate(sql1);
           if(n==1){
               jTextField3.setText(""); 
               jPanel2.setVisible(false);
               jPanel4.setVisible(false);
                receipt rpt=new receipt();
        rpt.setVisible(true);
        rpt.Order(order,jTextField2.getText());
        jTextField2.setText("");
          jTable1.setModel(new DefaultTableModel(null,new String[]{"Product Name","Type","Cost Per Unit","Quantity","Discount","Total"}));
              }
             }
             try{
            String sql3="insert into account values('"+check_in+"',"+point+",'"+GST+"','"+store_id+"')";
            stmt.executeUpdate(sql3);
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
        }
        }
        else{
            jLabel14.setVisible(true);
       
        
        }
        }
        catch(SQLException s){
           JOptionPane.showMessageDialog(this, s);
       }
         
      
       
         
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Product Name","Type","Cost Per Unit","Quantity","Discount","Total"}));
        jLabel8.setText("Total Cost");
         try{
            String sql3="insert into account values('"+check_in+"',"+point+",'"+GST+"','"+store_id+"')";
            stmt.executeUpdate(sql3);
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
        }
              try{
           String sql1="select phone_no,points from customer where phone_no='"+jTextField2.getText()+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               if(point>=10000){
               String sql2="update customer set points="+(Float.parseFloat(rs.getString("points"))+point/100)+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
              
           }
               else{
                     String sql2="update customer set points="+(Float.parseFloat(rs.getString("points")))+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
               }
           }
           else{
                if(point>=10000){
             String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"',"+point/100+",'"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
      
            }
            else{
                String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','0.00','"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
       
            }
           }
       }
       catch(SQLException e){
           
       }
        try{
             String sq="select cust_id from customer where phone_no='"+jTextField2.getText()+"'";
             rs=stmt.executeQuery(sq);
             if(rs.next()){
           String sql1="insert into payment(pay_name,amount_to_pay,cust_id,order_no) values('NET BANKING',"+point+",'"+rs.getString("cust_id")+"','"+order+"')";
          int n1= stmt.executeUpdate(sql1);
          if(n1==1){
              jPanel2.setVisible(false);
        jPanel4.setVisible(false);
        receipt rpt=new receipt();
        rpt.setVisible(true);
        rpt.Order(order,jTextField2.getText());
          }
           
      
                    }
                }
        catch(SQLException s){
        
        }
        
            jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Product Name","Type","Cost Per Unit","Quantity","Discount","Total"}));
        jLabel8.setText("Total Cost");
       try{
            String sql3="insert into account values('"+check_in+"',"+point+",'"+GST+"','"+store_id+"')";
            stmt.executeUpdate(sql3);
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
        }
              try{
           String sql1="select phone_no,points from customer where phone_no='"+jTextField2.getText()+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               if(point>=10000){
               String sql2="update customer set points="+(Float.parseFloat(rs.getString("points"))+point/100)+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
           }
               else{
                     String sql2="update customer set points="+(Float.parseFloat(rs.getString("points")))+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
               }
           }
           else{
                if(point>=10000){
            String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"',"+point/100+",'"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
          
              
            }
            else{
                String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','0.00','"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
      
            
            }
           }
       }
       catch(SQLException e){
           
       }
        try{
             String sq="select cust_id from customer where phone_no='"+jTextField2.getText()+"'";
             rs=stmt.executeQuery(sq);
             if(rs.next()){
           String sql1="insert into payment(pay_name,amount_to_pay,cust_id,order_no) values('CARD',"+point+",'"+rs.getString("cust_id")+"','"+order+"')";
          int n1= stmt.executeUpdate(sql1);
          if(n1==1){
              jPanel2.setVisible(false);
        jPanel4.setVisible(false);
              receipt rpt=new receipt();
        rpt.setVisible(true);
        rpt.Order(order,jTextField2.getText());
          }
           
      
                    }
                }
        catch(SQLException s){
        
        }
       jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new customerspoints(null, true).show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
     new item_details(null,true).show();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0){
           jLabel12.setVisible(true);
       }
       else{
       try{
          jLabel12.setVisible(false);
           String sql7="select store_id,GST from store";
        rs=stmt.executeQuery(sql7);
        if(rs.next()){
            store_id=rs.getString("store_id");
            GST=rs.getString("GST");
        }
       }
       catch(SQLException s){
           
       }
       try{
        String discount=null;
        String lic_no=null;
        String cost=null;
        String typ=null;
        float disc_mrp=0;
        int sl=0;
        String sql1="select * from productmanagement where product_name='"+jComboBox1.getSelectedItem()+"'";
       
         
        
         rs=stmt.executeQuery(sql1);
        
           while(rs.next()){
               p=rs.getString("product_name");
               cost=rs.getString("cost");
               typ=rs.getString("type");
               lic_no=rs.getString("lic_no");
               discount=rs.getString("discount");
               disc_mrp=rs.getFloat("disc_mrp");
           }
           float q=(float)jSpinner1.getValue();
          System.out.println(q);
           DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
           DateTimeFormatter dtf2=DateTimeFormatter.ofPattern("yyyy-MM-dd");

           DateTimeFormatter dtf1=DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
           LocalDateTime now=LocalDateTime.now();
        String sql4="select count(*) from addsells where order_no='"+b+"'";
        rs=stmt.executeQuery(sql4);
        
        if(rs.next()){
            sl=rs.getInt("count(*)");
            sl++;
        }
        mrp=Float.parseFloat(cost)*q;
        ttl=(Float.parseFloat(cost)*q)-((Float.parseFloat(cost))*q*(Float.parseFloat(discount))/100);
           String sql2="insert into addsells values("+sl+",'"+p+"','"+typ+"',"+q+",'"+cost+"',"+disc_mrp+","+mrp+","+ttl+",'"+b+"','"+a+"','"+GST+"','"+store_id+"','"+check_in+"')";
           
         int n= stmt.executeUpdate(sql2);//executeUpdate saves the data into the table 
            if(n==1){
                JOptionPane.showMessageDialog(this, n + " records saved successfully");
                 jPanel4.setVisible(true);
           }
            
        
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);//jTextField5.getText()+"\n already exist");
        } 
        try{
            //String item=(String)jComboBox1.getSelectedItem();
            String sql1="select * from addsells where order_no='"+b+"'";
            rs=stmt.executeQuery(sql1);
            
           DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("product_name"),rs.getString("type"),rs.getString("mrp_cost"),rs.getString("quantity"),rs.getString("disc_mrp"),rs.getString("disc_total")});
                quan=rs.getFloat("quantity");
            }
            
            String sql5="select sum(disc_total),max(sl_no) from addsells where order_no='"+b+"'";
            rs=stmt.executeQuery(sql5);
            while(rs.next()){
                jLabel8.setText("Total Cost:"+rs.getString("sum(disc_total)"));jLabel11.setText("No of Items: "+rs.getString("max(sl_no)"));
                 point=rs.getInt("sum(disc_total)");
            }
            try{
                String sql="update productmanagement set total_item=total_item-"+quan+" where product_name='"+p+"'";
                stmt.executeUpdate(sql);
            }
            catch(SQLException s){
                
            }
           
            
           
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
            
        }}
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jPanel5.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
       if(jTextField4.getText().isEmpty()){
         num="000";   
        }
        else{
            num=jTextField4.getText();
        }
         try{
           String sql1="select phone_no,points from customer where phone_no='"+num+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               if(point>10000){
               String sql2="update customer set points="+(Float.parseFloat(rs.getString("points"))+point/100)+" where phone_no='"+num+"'";
               stmt.executeUpdate(sql2);
               jTextField2.setText(num);
           }
               else{
                     String sql2="update customer set points="+(Float.parseFloat(rs.getString("points")))+" where phone_no='"+num+"'";
               stmt.executeUpdate(sql2);
                jTextField2.setText(num);
               }
           }
           
       }
       catch(SQLException e){
           
       }
       
       try{
            String sql1="select points from customer where phone_no='"+num+"'";
            rs=stmt.executeQuery(sql1);
            if(rs.next()){
                pnt=Float.parseFloat(rs.getString("points"));
                System.out.println(pnt);
                if(point>=pnt){
                    String sql2="update customer set points=0.00 where phone_no='"+num+"'";
                   int n= stmt.executeUpdate(sql2);
                   if(n==1){
                       point=(int) (point-pnt);
                      jLabel8.setText("Total Cost: "+point);
                       jTextField2.setText(num);
                   }
                    }
                else{
                    float rpoint=pnt-point;
                    System.out.println(rpoint);
                    String sql2="update customer set points="+rpoint+" where phone_no='"+num+"'";
                    int n=stmt.executeUpdate(sql2);
                    if(n==1){
                        point=0;
                      jLabel8.setText("Total Cost: 0");
                       jTextField2.setText(num);
                   }
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "not found");
            }
        }
        catch(SQLException e){

        }
      
       jTextField4.setText("");
       
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(num);
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Product Name","Type","Cost Per Unit","Quantity","Discount","Total"}));
        jLabel8.setText("Total Cost");
        receipt rpt=new receipt();
        rpt.setVisible(true);
        rpt.Order(order,num);
        
       
        try{
            String sql3="insert into account values('"+check_in+"',"+point+",'"+GST+"','"+store_id+"')";
            stmt.executeUpdate(sql3);
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, s);
        }
              try{
           String sql1="select phone_no,points from customer where phone_no='"+jTextField2.getText()+"'";
           rs=stmt.executeQuery(sql1);
           if(rs.next()){
               if(point>=10000){
               String sql2="update customer set points="+(Float.parseFloat(rs.getString("points"))+point/100)+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
           }
               else{
                     String sql2="update customer set points="+(Float.parseFloat(rs.getString("points")))+" where phone_no='"+jTextField2.getText()+"'";
               stmt.executeUpdate(sql2);
               jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
               }
           }
           else{
                if(point>=10000){
            String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','100.00','"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
            System.out.println(a);
            jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
            }
            else{
                String s="insert into customer values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','0.00','"+check_in+"','"+GST+"','"+store_id+"',0)";
            int a=stmt.executeUpdate(s);
            jTextField1.setText("");jTextField2.setText("");jTextField3.setText("");
            }
           }
       }
       catch(SQLException e){
           
       }
        try{
             String sq="select cust_id from customer where phone_no='"+jTextField2.getText()+"'";
             rs=stmt.executeQuery(sq);
             if(rs.next()){
           String sql1="insert into payment(pay_name,amount_to_pay,cust_id,order_no) values('POINTS',"+point+",'"+rs.getString("cust_id")+"','"+order+"')";
          int n1= stmt.executeUpdate(sql1);
          if(n1==1){
              jPanel2.setVisible(false);
        jPanel4.setVisible(false);
          }
           
      
                    }
                }
        catch(SQLException s){
        
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_sells.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_sells().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
