
import java.awt.Color;
import java.awt.Dialog;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cs_loneranger_
 */
public class Entry_page extends javax.swing.JFrame {
Connection connect;
Statement stmt;
ResultSet rs;
String name=null,sd=null;
boolean jtext1=false,jtext2=false,jtext3=false,jtext4=false;
public String name(String n,String a){
    name=n;
    sd=a;
    return "o";
}

public  int n;
    /**
     * Creates new form Entry_page
     */
    public Entry_page() {
        initComponents();
        Connectivity();
        jPanel2.setBackground(new Color(0,0,0,50));
        jPanel2.setVisible(false);
        jLabel9.setVisible(false);jLabel10.setVisible(false);jLabel11.setVisible(false);jLabel12.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Connectivity()
    {
        try{
       connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/provisionstore","root","tiger");
       stmt=connect.createStatement();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NEW EMPLOYEE SITE");

        jPanel1.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<-");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 20, 60, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("*O*SETTINGS");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPanel1.add(jLabel13);
        jLabel13.setBounds(970, 10, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(700, 510, 290, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("*EX:Arun35");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1000, 420, 110, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("*10 digits only");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(780, 300, 140, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("*EX:Arun");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1000, 110, 85, 22);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setText("SEARCH");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton1.setDoubleBuffered(true);
        jToggleButton1.setFocusCycleRoot(true);
        jToggleButton1.setFocusTraversalPolicyProvider(true);
        jToggleButton1.setHideActionText(true);
        jToggleButton1.setOpaque(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("SHOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store_images/cart.jpg"))); // NOI18N
        jLabel14.setText("CLOSE");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel14)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 30, 290, 300);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 120, 70, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(700, 110, 291, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("AGE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 170, 60, 25);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(700, 160, 291, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("GENDER");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 210, 90, 25);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(700, 210, 70, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(790, 210, 80, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton3.setText("OTHERS");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(900, 210, 77, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("MOBILE NUMBER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 280, 180, 25);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(700, 270, 291, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 350, 110, 22);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(700, 350, 291, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setText("CREATE ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 410, 110, 26);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(700, 420, 291, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("NEW PASSWORD");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 480, 180, 26);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(700, 480, 291, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(740, 550, 80, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store_images/Grocery_Blog_Post.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1130, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String gender;
       
        String empname=jTextField1.getText();
        String age=jTextField2.getText();
        if(jRadioButton1.isSelected()){
            gender=jRadioButton1.getText();
           
        }
        else if(jRadioButton2.isSelected()){
            gender=jRadioButton2.getText();
        }
        else{
            gender=jRadioButton3.getText();
          }
        String phone_number=jTextField4.getText();
        String address=jTextField5.getText();
        String emp_id=jTextField6.getText();
        String pass=jPasswordField1.getText();
        try{
            if(jPasswordField1.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "enter the details");
                jLabel9.setVisible(true);
                jLabel10.setVisible(true);
                jLabel11.setVisible(true);
                jPasswordField1.grabFocus();
                return;
            }
            else if(jtext1){
                if(jtext2){
                    if(jtext3){
                        if(jtext4){
            String sql="insert into newemployee values("+age+",'"+gender+"','"+phone_number+"','"+address+"','"+pass+"','"+emp_id+"','"+empname+"','"+sd+"')";
            int n= stmt.executeUpdate(sql); 
            if(n==1){
                JOptionPane.showMessageDialog(this, n + " record saved successfully");
                jTextField1.setText("");
                jTextField2.setText("");
                jLabel11.setVisible(false);
                jLabel12.setVisible(false);
                buttonGroup1.clearSelection();
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jPasswordField1.setText("");
                }
                    }
                        else{
                            jLabel12.setVisible(true);
                            jLabel12.setText("ENTER THE PASSWORD");
                        }
                     }
                    else{
                        jLabel11.setVisible(true);
                    }
            }
                else{
                    jLabel10.setVisible(true);
                }
            }
            else{
                jLabel9.setVisible(true);
            }
            
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, "employee ID:"+jTextField6.getText()+"\n already exist\n OR enter the correct age");
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                String emp_ID=jTextField6.getText();
      
        try{
            String sql="delete from newemployee where emp_ID='"+emp_ID+"'";
            int n= stmt.executeUpdate(sql);
            System.out.println(n);
            if(n==1){
                JOptionPane.showMessageDialog(this, n + " records deleted successfully");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jPasswordField1.setText("");
                }
            else{
                JOptionPane.showMessageDialog(this, "employee ID:"+jTextField6.getText()+"\n not found");
            }
        }
        catch(SQLException s){
            JOptionPane.showConfirmDialog(this,"employee ID:"+jTextField6.getText()+"\n not found");
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
         new employee_table(null,true).show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(jToggleButton1.isSelected()){
                if(jTextField6.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "enter the employee id!!");
                    jToggleButton1.setSelected(false);
                }

                else{String sql1="select * from newemployee where emp_ID='"+jTextField6.getText()+"'";
                    rs=stmt.executeQuery(sql1);

                    if(rs.next()){
                        jTextField1.setText(rs.getString("name"));
                        jTextField2.setText(rs.getString("age"));
                        // jTextField3.setText(rs.getString("sex"));
                        jTextField4.setText(rs.getString("phone"));
                        jTextField5.setText(rs.getString("address"));
                        jPasswordField1.setText(rs.getString("password"));
                        jTextField6.setText(rs.getString("emp_ID"));
                        jToggleButton1.setText("UPDATE");
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "ID not found!!");
                    }

                }

            }
            else{

                if(jRadioButton1.isSelected()){

                    String sql2="update newemployee set address='"+jTextField5.getText()+"',mang_ID='"+sd+"',name='"+jTextField1.getText()+"',age="+Integer.parseInt(jTextField2.getText())+",sex='"+jRadioButton1.getText()+"',phone="+jTextField4.getText()+",password='"+jPasswordField1.getText()+"' where emp_ID='"+jTextField6.getText()+"'";
                    n=stmt.executeUpdate(sql2);
                   
                }
                else if(jRadioButton2.isSelected()){
                    String sql2="update newemployee set address='"+jTextField5.getText()+"',mang_ID='"+sd+"',name='"+jTextField1.getText()+"',age="+Integer.parseInt(jTextField2.getText())+",sex='"+jRadioButton2.getText()+"',phone="+jTextField4.getText()+",password='"+jPasswordField1.getText()+"'where emp_ID='"+jTextField6.getText()+"'";
                    n=stmt.executeUpdate(sql2);
                    
                }
                else{
                    String sql2="update newemployee set address='"+jTextField5.getText()+"',mang_ID='"+sd+"',name='"+jTextField1.getText()+"',age="+Integer.parseInt(jTextField2.getText())+",sex='"+jRadioButton3.getText()+"',phone="+jTextField4.getText()+",password='"+jPasswordField1.getText()+"' where emp_ID='"+jTextField6.getText()+"'";
                    n=stmt.executeUpdate(sql2);
                    
                }

                if(n==1){
                   JOptionPane.showMessageDialog(this,"DETAILS UPDATED SUCCESSFULLY");
                   buttonGroup1.clearSelection();
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jPasswordField1.setText("");
                    jToggleButton1.setText("SEARCH");
                }
            }
        }
        catch(SQLException s){
            System.out.println(s);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        boolean mat= Pattern.matches("[a-z]*", jTextField1.getText());
        if(mat){
            jLabel9.setVisible(false);
            jtext1=mat;
        }
        else{
            jLabel9.setVisible(true);
            jtext1=mat;
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        boolean mat= Pattern.matches("[a-z]*", jTextField1.getText());
        if(mat){
            jLabel9.setVisible(false);
            jtext1=mat;
        }
        else{
            jLabel9.setVisible(true);
            jtext1=mat;
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        boolean mat= Pattern.matches("[a-z]*", jTextField1.getText());
        if(mat){
            jLabel9.setVisible(false);
            jtext1=mat;
        }
        else{
            jLabel9.setVisible(true);
            jtext1=mat;
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
              boolean phone1=Pattern.matches("[6789][0-9]{9}",jTextField4.getText().trim());
       if(phone1){
            jLabel10.setVisible(false);
            jtext2=phone1;
        }
        else{
            jLabel10.setVisible(true);
            jtext2=phone1;
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
                    boolean phone1=Pattern.matches("[6789][0-9]{9}",jTextField4.getText().trim());
       if(phone1){
            jLabel10.setVisible(false);
            jtext2=phone1;
        }
        else{
            jLabel10.setVisible(true);
            jtext2=phone1;
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
                    boolean phone1=Pattern.matches("[6789][0-9]{9}",jTextField4.getText().trim());
       if(phone1){
            jLabel10.setVisible(false);
            jtext2=phone1;
        }
        else{
            jLabel10.setVisible(true);
            jtext2=phone1;
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
          boolean id=Pattern.matches("([a-z A-Z]*)([0-9]*)", jTextField6.getText());
        if(id){
          jLabel11.setVisible(false);
           jtext3=id;
        }
        else{
            jLabel11.setVisible(true);
             jtext3=id;
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
          boolean id=Pattern.matches("([a-z A-Z]*)([0-9]*)", jTextField6.getText());
        if(id){
          jLabel11.setVisible(false);
           jtext3=id;
        }
        else{
            jLabel11.setVisible(true);
             jtext3=id;
        }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
          boolean id=Pattern.matches("([a-z A-Z]*)([0-9]*)", jTextField6.getText());
        if(id){
          jLabel11.setVisible(false);
           jtext3=id;
        }
        else{
            jLabel11.setVisible(true);
             jtext3=id;
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
          boolean bad=Pattern.matches("[a-z A-Z]*||[0-9]*", jPasswordField1.getText());
        if(bad){
            jLabel12.setVisible(true);jLabel12.setText("atleast 1 special character");
            jtext4=false;
        }
        else{
            jLabel12.setVisible(true);jLabel12.setText("strong");
            jtext4=true;
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
          boolean bad=Pattern.matches("[a-z A-Z]*||[0-9]*", jPasswordField1.getText());
        if(bad){
            jLabel12.setVisible(true);jLabel12.setText("atleast 1 special character");
            jtext4=false;
        }
        else{
            jLabel12.setVisible(true);jLabel12.setText("strong");
            jtext4=true;
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
          boolean bad=Pattern.matches("[a-z A-Z]*||[0-9]*", jPasswordField1.getText());
        if(bad){
            jLabel12.setVisible(true);jLabel12.setText("atleast 1 special character");
            jtext4=false;
        }
        else{
            jLabel12.setVisible(true);jLabel12.setText("strong");
            jtext4=true;
        }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel13.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        jLabel13.setForeground(Color.white);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setForeground(Color.black);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
          store_page sp=new store_page();
        sp.setVisible(true);
        sp.connect(name,sd);
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel15.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
         jLabel15.setForeground(Color.white);
    }//GEN-LAST:event_jLabel15MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entry_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entry_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entry_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entry_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entry_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
