
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cs_loneranger_
 */
public class receipt extends javax.swing.JFrame {
Connection connect;
Statement stmt;
ResultSet rs;
String r=null,s=null,s2=null;
float a=0,b=0;
public void Order(String o,String p){
    r=o;
    s=p;
    //System.out.println(r);
   }
public void order1(String q){
    q=s2;
}
/**
     * Creates new form receipt
     */
    public receipt() {
        
        initComponents();
        //jTextArea1.setEditable(false);
        Connectivity();
    }
    public void Connectivity(){
         try{
       connect=DriverManager.getConnection("jdbc:mysql://localhost:3306/provisionstore","root","tiger");
       stmt=connect.createStatement();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BILL");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                abc(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abc(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_abc
        // TODO add your handling code here:
        try{
            String sql2="select * from store";
            rs=stmt.executeQuery(sql2);
            if(rs.next()){
             jTextArea1.append("\t\t\t\t\t\t\t\t   "+rs.getString("store_name")+"\n");
            jTextArea1.append("\t\t\t\t\t\t\t\t     "+rs.getString("area")+"\n");
            jTextArea1.append("\t\t\t\t\t\t     "+rs.getString("landarea")+"\n");
            jTextArea1.append("\t\t\t\t\t\t\t\t  "+"Phone:"+rs.getString("phone")+"\n");
            jTextArea1.append("\t\t\t\t\t\t               GSTIN:"+rs.getString("GST")+"\n"+"\t\t\t                                      Invoice/Bill of Supply\n\n");
            jTextArea1.append("BILL NO:"+r+"\n");
           }
           
             String s="select sum(total)-sum(disc_total) as savings from addsells where order_no='"+r+"'";
             rs=stmt.executeQuery(s);
             if(rs.next()){
                 a=rs.getFloat("savings");
                 if(a!=0){
              jTextArea1.append("YOU HAVE SAVED RS:  "+rs.getString("savings")+" OUR PRICE IS INCLUSIVE OF ALL GST\n\n\n");
             jTextArea1.append("ITEMS ARE LESSER THEN THE MRP PRICE\n\n\n");
               }
             }
            }
        catch(SQLException e){
            
        }
        try{
            String sql="select points from customer where phone_no='"+s+"' or phone_no='"+s2+"'";
            rs=stmt.executeQuery(sql);
            if(rs.next()){
                jTextArea1.append("POINTS:"+rs.getString("points")+"\n");
            }
                jTextArea1.append("\"---------------------------------------------------------------------------------------------------------------------\n");
                jTextArea1.append("PARTICULARS\t\t\tTYPE\t\t\tMRP\t\t\tDISC(mrp)\t\t\tQTY\t\t\tAMOUNT\n");
            
        }
        catch(SQLException s){
            
        }
        
         try{
            String sql1="select * from addsells where order_no='"+r+"'";
            rs=stmt.executeQuery(sql1);
             
             while(rs.next()){
            jTextArea1.append(rs.getString("product_name")+"\t\t\t"+rs.getString("type")+"\t\t\t"+rs.getString("mrp_cost")+"\t\t\t"+rs.getString("disc_mrp")+"\t\t\t"+rs.getString("quantity")+"\t\t\t"+rs.getString("disc_total")+"\n");
             }
            
            //rs.getString("emp_ID")
           
        }
        catch(SQLException s){
            JOptionPane.showMessageDialog(this, "empty relation");
            
        }
         jTextArea1.append("---------------------------------------------------------------------------------------------------------------------\n");
         try{
             String sql1="select max(sl_no) from addsells where order_no='"+r+"'";
            rs=stmt.executeQuery(sql1);
            if(rs.next()){
                jTextArea1.append("No Of Items:"+rs.getString("max(sl_no)")+"\n");
            }
         }
         catch(SQLException s){
             
         }
         try{
            String sql3="select * from payment where order_no='"+r+"'";
            rs=stmt.executeQuery(sql3);
            if(rs.next()){
                jTextArea1.append("TOTAL:"+rs.getString("amount_to_pay")+"\n"+"PAYMENT METHOD:"+rs.getString("pay_name")+"\n"+"CASH PAID:"+rs.getString("cash_paid")+"\n"+"CHANGE DUE:"+rs.getString("change_due")+"\n");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }         
         jTextArea1.append("---------------------------------------------------------------------------------------------------------------------\n");
        
         jTextArea1.append("\t\t\t\t\t\t\t Goods Once Sold Will not be Taken Back\n");
         jTextArea1.append("\t\t\t\t\t\t              THANK YOU VISIT AGAIN");


    }//GEN-LAST:event_abc

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
